### ISSUE TITLE
verifyPact internal verification in tests fail, but verifyPact from sbt works.

### ISSUE THREAD

**Issue by jnatten** [ITV/scala-pact#106]
This is almost certainly me doing something terribly wrong, so please excuse my stupidity.
Running scala-pact version `2.3.3`.
I'm trying to setup scala-pact and have gotten my consumer to generate a pact looking something like this:
```
{
  "provider" : {
    "name" : "Provider"
  },
  "consumer" : {
    "name" : "Consumer"
  },
  "interactions" : [
    {
      "request" : {
        "method" : "GET",
        "path" : "/api/v1/agreements/1"
      },
      "description" : "Fetching agreement with id 1",
      "response" : {
        "status" : 200,
        "body" : {
          "id" : 1
        }
      }
    }
  ]
}
```
Which seems correct. Then i have implemented a test looking pretty much like the example (https://github.com/ITV/scala-pact/blob/master/example/provider_tests/src/test/scala/com/example/provider/VerifyContractsSpec.scala)

Simply launching the database + Jetty server and setting up some state in beforeAll()
With a test like this:
```
  describe("verify contracts pls") {
    it("should work pls") {
      verifyPact
        .withPactSource(loadFromLocal("delivered_pacts"))
        .setupProviderState("given") { _ => ProviderStateResult(true) }
        .runVerificationAgainst("http", "localhost", serverPort)
    }
  }
```

This crashes: 
```
Attempting to use local pact files at: 'delivered_pacts'
Verifying against 'localhost' on port '37707' with a timeout of 2 second(s).
Results for pact between Consumer and Provider
 - [FAILED] Fetching agreement with id 1
cats.effect.IO$.ioConcurrentEffect()Lcats/effect/ConcurrentEffect;
[scala-pact] Run completed in: 59 ms
[scala-pact] Total number of test run: 1
[scala-pact] Tests: succeeded 0, failed 1
[scala-pact] 1 Pact verify tests failed.

com.itv.scalapact.ScalaPactVerify$ScalaPactVerifyFailed was thrown.
com.itv.scalapact.ScalaPactVerify$ScalaPactVerifyFailed
	at com.itv.scalapact.ScalaPactVerify$verifyPact$ScalaPactVerifyRunner.doVerification(ScalaPactVerify.scala:216)
	at com.itv.scalapact.ScalaPactVerify$verifyPact$ScalaPactVerifyRunner.runVerificationAgainst(ScalaPactVerify.scala:91)
	at no.ndla.draftapi.VerifyContractsTest.$anonfun$new$2(VerifyContractsTest.scala:95)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
	at org.scalatest.FunSpecLike.invokeWithFixture$1(FunSpecLike.scala:452)
	at org.scalatest.FunSpecLike.$anonfun$runTest$1(FunSpecLike.scala:464)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSpecLike.runTest(FunSpecLike.scala:464)
	at org.scalatest.FunSpecLike.runTest$(FunSpecLike.scala:446)
	at org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
	at org.scalatest.FunSpecLike.$anonfun$runTests$1(FunSpecLike.scala:497)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSpecLike.runTests(FunSpecLike.scala:497)
	at org.scalatest.FunSpecLike.runTests$(FunSpecLike.scala:496)
	at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
	at org.scalatest.FunSpecLike.$anonfun$run$1(FunSpecLike.scala:501)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSpecLike.run(FunSpecLike.scala:501)
	at org.scalatest.FunSpecLike.run$(FunSpecLike.scala:500)
	at no.ndla.draftapi.VerifyContractsTest.org$scalatest$BeforeAndAfterAll$$super$run(VerifyContractsTest.scala:16)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at no.ndla.draftapi.VerifyContractsTest.run(VerifyContractsTest.scala:16)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```
If i set a breakpoint right before `verifyPact` runs, i can query the server and it seems to be correctly setup.
Calling `sbt "pactVerify --host localhost --port 37707 --protocol http --source delivered_pacts"`

**Comment by davesmith00000** [comment]
That is a very unhelpful error message! :-)
I'll start with the easy questions and then we'll dig further if we need to (and either way I'll try and improve the error).
You've generated the pact contract file you mentioned above, and I assume you did that by running `sbt pactTest` or `sbt test pactPack`. That would have placed the contract file into your projects normal target directory.
The verify job is exacting the pact file to be in a folder at the root of the provider project called `delivered_pacts`. Have you copied and pasted the generated pact file into that location?

**Comment by jnatten** [comment]
I generated the file by running `sbt pactTest`, and copied the file from consumerDir/target/pacts to providerdir/delivered_pacts.

I am pretty sure the pact is found considering i get a different error message when attempting to specify an empty directory. (`[scala-pact] No Pact verification tests run.` rather than `[scala-pact] 1 Pact verify tests failed.`)

**Comment by davesmith00000** [comment]
Ah Sorry! I think perhaps I missed the point.
`sbt pactVerify` is for external verification. i.e. You're running a real (albeit local) version of the service and you're asking Scala-Pact to fire requests at it.
However, you've set up and internal verification, which just runs in a test suite:
```
describe("verify contracts pls") {
    it("should work pls") {
      verifyPact
      ...
```
So all you need to do is run `sbt test` and it should just work.
Or is that what you are doing and you're still getting the error?
If you're still getting the error, then I suspect it is to do with the lifecycle of the service, which got much much harder to manage from version 0.18 of http4s onwards (I assume that's the framework you're using?).
One thing to try: Can you just make an HTTP request inside the test suite to the running mock and println the status to make sure it's still running? (I don't use breakpoints much so I don't get much comfort from that test you have at the moment.)

**Comment by jnatten** [comment]
I am already running `sbt test` and getting the error.
We're using jetty (scalatra) as the http server for the provider.

Doing an http request from within the test suite is pretty much what i tried to explain with the breakpoint.
I also tested it with scalaj.http.Http and got the same result (200 OK with expected body).

**Comment by jnatten** [comment]
I did some digging and turns out there is a incompatibility somewhere with cats.
When i remove
`"org.typelevel" %% "cats-effect" % "1.0.0"` from build.sbt the test seems to pass just fine.

**Comment by jnatten** [comment]
Can't seem to figure out how to avoid this without removing cats. 
What is the correct way to use cats with scala-pact? @davesmith00000 

Btw, this is the stacktrace leading to the `cats.effect.IO$.ioConcurrentEffect()Lcats/effect/ConcurrentEffect;` part of the error.
```
java.lang.NoSuchMethodError: cats.effect.IO$.ioConcurrentEffect()Lcats/effect/ConcurrentEffect;

com.itv.scalapact.http4s18.impl.Http4sClientHelper$.buildPooledBlazeHttpClient(Http4sClientHelper.scala:39)
com.itv.scalapact.http4s18.impl.ScalaPactHttpClient.$anonfun$doInteractionRequestIO$6(ScalaPactHttpClient.scala:68)
com.itv.scalapact.shared.SslContextMap$.apply(SslContextMap.scala:46)
com.itv.scalapact.http4s18.impl.ScalaPactHttpClient.doInteractionRequestIO(ScalaPactHttpClient.scala:65)
com.itv.scalapact.http4s18.impl.ScalaPactHttpClient.doInteractionRequestSync(ScalaPactHttpClient.scala:37)
com.itv.scalapactcore.verifier.Verifier$.$anonfun$doRequest$1(Verifier.scala:193)
scala.Function1.$anonfun$andThen$1(Function1.scala:52)
com.itv.scalapactcore.verifier.Verifier$.$anonfun$verify$12(Verifier.scala:74)
scala.collection.immutable.List.map(List.scala:282)
com.itv.scalapactcore.verifier.Verifier$.$anonfun$verify$11(Verifier.scala:67)
scala.collection.immutable.List.map(List.scala:282)
com.itv.scalapactcore.verifier.Verifier$.$anonfun$verify$1(Verifier.scala:64)
com.itv.scalapactcore.verifier.Verifier$.$anonfun$verify$1$adapted(Verifier.scala:21)
com.itv.scalapact.ScalaPactVerify$verifyPact$ScalaPactVerifyRunner.doVerification(ScalaPactVerify.scala:216)
com.itv.scalapact.ScalaPactVerify$verifyPact$ScalaPactVerifyRunner.runVerificationAgainst(ScalaPactVerify.scala:79)
no.ndla.draftapi.VerifyContractsSpec.$anonfun$new$2(VerifyContractsSpec.scala:92)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
org.scalatest.Transformer.apply(Transformer.scala:22)
org.scalatest.Transformer.apply(Transformer.scala:20)
org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
org.scalatest.FunSpecLike.invokeWithFixture$1(FunSpecLike.scala:452)
org.scalatest.FunSpecLike.$anonfun$runTest$1(FunSpecLike.scala:464)
org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
org.scalatest.FunSpecLike.runTest(FunSpecLike.scala:464)
org.scalatest.FunSpecLike.runTest$(FunSpecLike.scala:446)
org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
org.scalatest.FunSpecLike.$anonfun$runTests$1(FunSpecLike.scala:497)
org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
scala.collection.immutable.List.foreach(List.scala:388)
org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
scala.collection.immutable.List.foreach(List.scala:388)
org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
org.scalatest.FunSpecLike.runTests(FunSpecLike.scala:497)
org.scalatest.FunSpecLike.runTests$(FunSpecLike.scala:496)
org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
org.scalatest.Suite.run(Suite.scala:1147)
org.scalatest.Suite.run$(Suite.scala:1129)
org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
org.scalatest.FunSpecLike.$anonfun$run$1(FunSpecLike.scala:501)
org.scalatest.SuperEngine.runImpl(Engine.scala:521)
org.scalatest.FunSpecLike.run(FunSpecLike.scala:501)
org.scalatest.FunSpecLike.run$(FunSpecLike.scala:500)
no.ndla.draftapi.VerifyContractsSpec.org$scalatest$BeforeAndAfterAll$$super$run(VerifyContractsSpec.scala:16)
org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
no.ndla.draftapi.VerifyContractsSpec.run(VerifyContractsSpec.scala:16)
org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
scala.collection.immutable.List.foreach(List.scala:388)
org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
org.scalatest.tools.Runner$.run(Runner.scala:850)
org.scalatest.tools.Runner.run(Runner.scala)
org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)

```

**Comment by davesmith00000** [comment]
Could you try changing your deps to use these ones and se what happens?
```
  "com.itv" %% "scalapact-argonaut-6-2" % "2.3.3" % "test",
  "com.itv" %% "scalapact-http4s-0-16a" % "2.3.3" % "test",
  "com.itv" %% "scalapact-scalatest"        % "2.3.3" % "test"
```

**Comment by davesmith00000** [comment]
You might also need to update how the plugin is installed like this:
```
 libraryDependencies ++= Seq(
   "com.itv" %% "scalapact-argonaut-6-2" % "2.3.3",
   "com.itv" %% "scalapact-http4s-0-16a" % "2.3.3"
 )
 
 addSbtPlugin("com.itv" % "sbt-scalapact-nodeps" % "2.3.3")
```
If 16a works, you could also try the 17 version:
`"com.itv" %% "scalapact-http4s-0-17" % "2.3.3"`

**Comment by jnatten** [comment]
It seems to work with 16a. Thanks! :)

**Comment by davesmith00000** [comment]
Glad to hear that your sorted.
The reason it works is that 16a are argonaut don't use Cats, and between Cats versions they've broken the API's somewhere along the line. Even though 16a and argonaut are older versions it won't/shouldn't make a difference to your testing experience.
Many people have many complaints about Scala - usually compile times - but my biggest headache by miles is dependency hell/library conflicts.
